version: 0.2

env:
  variables:
    DOCKER_REPOSITORY: "colehansen"
    DOCKER_IMAGE: "cds-slavetrade"

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $DOCKER_REPOSITORY/$DOCKER_IMAGE:$DOCKER_TAG .
  post_build:
    commands:
      - docker push $DOCKER_REPOSITORY/$DOCKER_IMAGE:$DOCKER_TAG
      - echo Build completed on `date`
